POST http://localhost:8080/api/currency/value/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="currency_id"

1
--WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="value"

1
--WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="created_at"

2020-10-10
--WebAppBoundary



###
