POST http://localhost:8080/api/currency/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

RUB
--WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="full_name"

Russian Rouble
--WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="symbol"

₽
--WebAppBoundary

###
