<?php

namespace src\Repository;

/**
 * CurrencyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByDate(\Datetime $from, \DateTime $to)
    {
        $qb = $this->createQueryBuilder("e");
        $qb
            ->andWhere('e.created_at BETWEEN :from AND :to')
            ->setParameter('from', $from )
            ->setParameter('to', $to)
        ;
        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
